import type { Incident } from "./IncidentAccordion";

export const incidents: Incident[] = [
  {
    id: "INC-01",
    title: "Query Shape, Not Tuning",
    category: "Diagnosis · query architecture",
    when: "2022",
    duration: "3 hours",
    impact: "Cross-team, blocking",
    sections: [
      { heading: "Problem", body: "Paginated queries timing out. Team had exhausted index tuning — every optimization lever was maxed. Root issue: join happened before pagination. Materializing millions of rows, then limiting to 100, is cardinality inversion." },
      { heading: "Solution", body: "Reverse operation order: LIMIT from primary table first, then join only for those 100 rows. Changed cardinality from millions-in-join to 100-in-join." },
      { heading: "Result", body: "Response time: 3+ minutes → under 500ms (360x faster). Key insight: separates query tuning from query architecture." },
    ],
  },
  {
    id: "INC-02",
    title: "MySQL Lock Contention at Scale",
    category: "Crisis · production isolation",
    when: "Early 2022",
    duration: "1–1.5 days",
    impact: "Production-wide, all 200+ merchants",
    sections: [
      { heading: "Problem", body: "Post-cutover response time spiked from seconds to 5+. Root cause: MySQL LOAD DATA holds locks for the entire operation. With 6 parallel threads per client across 200+ merchants, hundreds of concurrent lock holders — everything downstream waited." },
      { heading: "Solution", body: "Reduced parallelism from 6 → 3 concurrent load threads. Released locks sooner, allowing downstream queries to proceed." },
      { heading: "Result", body: "Response time returned to baseline. Key insight: production scale ≠ staging scale." },
    ],
  },
  {
    id: "INC-03",
    title: "Real-Time Product Changes in Recommendations",
    category: "Product judgment · customer signal",
    when: "2022–2023",
    duration: "3–4 days",
    impact: "Churn driver — stale recommendations",
    sections: [
      { heading: "Problem", body: "Old system precalculated every 24 hours. If a product went out of stock at hour 7, it stayed in recommendations for 17 more hours. Merchants lost trust; CSMs complained, though it never surfaced in sprint planning." },
      { heading: "Solution", body: "Webhook → MySQL landing → Debezium → Pub/Sub. Real-time messages on product updates; consuming services listen and update blocks in real-time." },
      { heading: "Result", body: "Recommendation freshness improved from a 24-hour batch cycle to a maximum 5-minute lag. Key insight: listen to customer-facing teams, not only tickets." },
    ],
  },
  {
    id: "INC-04",
    title: "MySQL Views → Debezium CDC",
    category: "Architecture · deadline judgment",
    when: "2022–2023",
    duration: "Phase 1: 2 months, Phase 2: 1 month",
    impact: "Foundation of data platform architecture",
    sections: [
      { heading: "Problem", body: "MySQL views for normalized serving materialize the entire dataset before applying filters. COUNT(*) on one client read millions of rows — queries took 30+ seconds." },
      { heading: "Phase 1 (urgent)", body: "Converted views to CTEs, applying filters before joins. Bought 2 months: 30s → 1.5-2s." },
      { heading: "Phase 2 (proper fix)", body: "Debezium tails MySQL → Pub/Sub. Services normalize into purpose-shaped stores: MongoDB for point lookups, ClickHouse for aggregation." },
      { heading: "Result", body: "Phase 2 achieved the same latency as Phase 1 with a different, correct approach — it became the platform architecture. Key insight: normalize in consumers, not the database." },
    ],
  },
  {
    id: "INC-05",
    title: "Missing Index on Production Query",
    category: "Operational discipline · prevention",
    when: "One week after deployment",
    duration: "3–4 hours",
    impact: "Intermittent performance degradation",
    sections: [
      { heading: "Problem", body: "Consuming service response time spiked intermittently. Root cause: a query filtered on a MongoDB field without an index — only certain queries hit it." },
      { heading: "Solution", body: "Added the index immediately. Permanently, added query-performance monitoring: if response drops below threshold, alert immediately." },
      { heading: "Result", body: "Monitoring now prevents similar regressions in minutes, not days. Key insight: process gaps matter as much as technical fixes." },
    ],
  },
  {
    id: "INC-06",
    title: "Real-Time Optimization Gone Wrong",
    category: "Leadership · stability tradeoff",
    when: "December 24 (Christmas Eve)",
    duration: "12 hours",
    impact: "Production-wide, peak sales, org-wide panic",
    sections: [
      { heading: "Problem", body: "A team member optimized recommendation sorting to update ClickHouse on every real-time product change, without understanding its memory constraints. With millions of products and real-time traffic, the database ran out of memory — a silent failure where reports looked correct but weren't." },
      { heading: "Solution", body: "Immediately scaled ClickHouse RAM for breathing room. Permanently, implemented a 24-hour batch solution — and had the engineer own the fix as a learning opportunity, plus added AI-assisted code review to flag similar patterns." },
      { heading: "Result", body: "Christmas sales unblocked, process improved, team member learned. Key insight: crisis management plus mentorship under pressure." },
    ],
  },
  {
    id: "INC-07",
    title: "Repeated Pattern: Segment Ordering",
    category: "Pattern recognition · systems thinking",
    when: "2023, then 2023–2024",
    duration: "4 days, then 4 hours",
    impact: "Wrong audience got emails",
    sections: [
      { heading: "First incident", body: "No explicit ORDER BY in the segment API. BigQuery returns results in non-guaranteed order — emails sent to the wrong audience. Fixed with explicit ordering." },
      { heading: "Second incident (BQ → ClickHouse)", body: "Copied the query from BigQuery to ClickHouse without realizing its ORDER BY semantics differ (NULL handling, tie-breaking). Same problem resurfaced — the same customer churned twice." },
      { heading: "Systemic fix", body: "Three layers: producer maintains the API contract and ordering guarantee; consumers validate incoming data matches expected ordering before sending emails; continuous QA validation across all services." },
      { heading: "Result", body: "Ordering validated continuously. Key insight: recognize when problems repeat, and build systems to prevent it." },
    ],
  },
  {
    id: "INC-08",
    title: "Silent Failure, Fixed Algorithmically",
    category: "Algorithms · correctness under constraint",
    when: "BQ → ClickHouse migration, 2023–2024",
    duration: "2.5 weeks",
    impact: "Correctness issue (silent failure) + cost",
    sections: [
      { heading: "Problem", body: "Segment comparison to identify new/removed/unchanged members worked via full outer join on BigQuery (expensive but correct). On ClickHouse, comparing 100M members hit memory limits — O(n²) memory. Scaling up RAM produced results that looked successful but were silently wrong." },
      { heading: "Root cause", body: "Trying to move BigQuery's unlimited-memory join model into ClickHouse's tight-memory budget — an incompatibility, not a tuning problem." },
      { heading: "Solution: batched hashing with cityHash64", body: "Partition both old and new segments deterministically with cityHash64, so the same email falls into the same bucket in both datasets. Compare bucket by bucket via hashes, investigating only buckets whose hashes differ — memory stays bounded instead of scaling with the full comparison." },
      { heading: "Result", body: "Memory: unlimited → 16GB fixed. Cost: ₹3+ lakhs → ₹50K (6x reduction). Correctness restored. Key insight: recognize incompatibility, solve algorithmically instead of throwing resources at it." },
    ],
  },
  {
    id: "INC-09",
    title: "ClickHouse Materialized-View Scale Mismatch",
    category: "Database behavior · scale judgment",
    when: "BigQuery → ClickHouse migration, 2023–2024",
    duration: "~2 weeks",
    impact: "Production reports degrading",
    sections: [
      { heading: "Problem", body: "ClickHouse materialized views auto-refresh when underlying tables change, but the view queries (aggregations + joins) were rescanning large tables at hundreds of events per second. CPU spiked; reports took minutes to return." },
      { heading: "Solution", body: "Replaced real-time materialized views with a scheduled hourly batch refresh — precomputing aggregations once per hour instead of on every row arrival." },
      { heading: "Result", body: "Stable CPU, predictable cost, reports under 30 seconds. Key insight: database-specific behavior matters more than architectural desire for real-time." },
    ],
  },
  {
    id: "INC-10",
    title: "Node.js Memory and Backpressure",
    category: "Resilience · platform pattern",
    when: "Early 2024",
    duration: "~3 weeks",
    impact: "Recurring daily OOM crashes, on-call burden",
    sections: [
      { heading: "Problem", body: "Pub/Sub-consuming Node.js services hit daily OOMs at a 512MiB pod limit — pulling messages as fast as Pub/Sub delivered them with no regard for available heap. It looked like a code-level memory leak, but local testing showed nothing; the failure only surfaced under production traffic volume." },
      { heading: "Solution", body: "Implemented backpressure: monitor heap usage in real time, pause consumption at an 80% high-water mark, resume at 60%. Messages queue safely in Pub/Sub meanwhile. Combined with Kubernetes HPA for burst traffic." },
      { heading: "Result", body: "Crashes went from recurring to essentially eliminated. The pause/resume pattern was adopted across consuming services platform-wide. Key insight: constraints matter more than code — a pod memory limit is real, and feedback loops beat throwing resources at the symptom." },
    ],
  },
];
